var dataset = [
["Abbé de l'Epée", 1755, "international", "Abbé Charles-Michel de l’Epée (* 25. November 1712 in Versailles; † 23. Dezember 1789 in Paris) war ein Pionier der Gehörlosenpädagogik.<br><a href='http://google.de'>Quelle</a>", "Paris"],
  ["Pierre Desogles", 1779, "international", "xxx", "Paris"],
  ["Beginn der französischen Revolution", 1789, "international", "Französische Revolution. Am 14. Juli des Jahres 1789: Aufständische greifen ein Gefängnis in Paris an, die Bastille. Die Gefangenen der alten Herrscher sollten befreit werden. Dies gilt als Beginn der Revolution. Quelle:", "France"],
  ["Ende der französischen Revolution", 1799, "international", "xxx", "France"],
  ["Gallaudet University", 1816, "international", "Die Gallaudet University in Washington, D.C. ist die erste Universität für gehörlose und schwerhörige Studenten und die einzige, die ihr gesamtes Programm und sämtliche Leistungen speziell auf diese Studenten angepasst hat. Die Einrichtung wurde am 16. Februar 1857, zunächst nur als Schule, in Washington, D.C. als «Columbia Institution for the Deaf and Dumb and the Blind» vom US-Postminister Amos Kendall gegründet. Kendal...", "Washington D.C."],
  ["Blinden- und Taubstummenanstalt", 1827, "switzerland", "xxx", "Zurich"],
  ["Eugen Sutermeister", 1862, "switzerland", "xxx", "Switzerland"],
  ["Mailänder Kongress", 1880, "international", "xxx", "Milano"],
  ["Schweizerischen Taubstummenzeitung", 1907, "switzerland", "xxx", "Switzerland"],
  ["Fürsorgeverein für Taubstummen (heute Sonos)", 1911, "switzerland", "xxx", "Switzerland"],
  ["Schweizerischen Verband für Taubstummenhilfe", 1933, "switzerland", "xxx", "Switzerland"],
  ["Schweizerische Gesellschaft der Gehörlosen (SGdG)", 1946, "switzerland", "xxx", "Switzerland"],
  ["World Federation of the Deaf", 1951, "international", "Weltverband der Gehörlosen WFD gegründet", "Rom"],
  ["Berufsschule", 1954, "switzerland", "SVT übernimmt die Trägerschaft der Berufsschule", "Switzerland"],
  ["WFD in Schweiz", 1957, "switzerland", "SGB tritt Weltverband der Gehörlosen (WFD)", "Switzerland"],
  ["Struktur der Gebärdensprache", 1960, "international", "William Stocke - beweist dass die Gebärdensprache struktur hat.", "USA"],
  ["xxx", 1977, "switzerland", "Schweizerischen Verband für das Gehörlosenwesen SVG", "Switzerland"],
  ["xxx", 1980, "switzerland", "Erste Forschung zur Gebärdnesprache DSGS", "Switzerland"],
  ["xxx", 1985, "international", "Gründung des European Community Regional Secretariat, das am 10. Oktober 1994 in European Union of the Deaf umbenannt wurde", "London"],
  ["Oscar für erste gehörlose Filmschauspielerin", 1987, "international", "Marlee Beth Marlin Oscar als beste Hauptdarstellerin in Gottes vergessene Kinder.", "USA"],
  ["???", 2001, "switzerland", "Schweizerischer Verband für Gehörlosen und Hörgeschädigten-Organisationen SONOS", "Switzerland"],
  ["Gleiche Rechte für Behinderte", 2003, "switzerland", "Ablehnung der Abstimmung über die Volksinitiative «Gleiche Rechte für Behinderte».", "Switzerland"]
];
var yeardata = [1600, 1700, 1800, 1900, 2000, 2100, 1610, 1620, 1630, 1640, 1650, 1660, 1670, 1680, 1690, 1710, 1720, 1730, 1740, 1750, 1760, 1770, 1780, 1790, 1810, 1820, 1830, 1840, 1850, 1860, 1870, 1880, 1890, 1910, 1920, 1930, 1940, 1950, 1960, 1970, 1980, 1990, 2010, 2020, 2030, 2040, 2050, 2060, 2070, 2080, 2090]
